name: Deploy Java
on:
  workflow_run:
    workflows: ["Push tag"]
    types:
      - completed
jobs:
  deploy-java:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ğŸ›ï¸
        uses: actions/checkout@v2
      - name: Install Haxe ğŸ“¥
        run: |
          sudo add-apt-repository ppa:haxe/releases -y
          sudo apt update
          sudo apt install haxe -y
          mkdir ~/haxelib && haxelib setup ~/haxelib
          yes | haxelib install package.hxml
      - name: Build package ğŸ”§
        run: haxe package.hxml
      - name: Deploy to Maven Central ğŸš€
        run: |
          openssl aes-256-cbc -K $encrypted_6c315054a92d_key -iv $encrypted_6c315054a92d_iv -in stuff/key.gpg.enc -out stuff/key.gpg -d
          gpg --batch --passphrase ${mvn_passphrase} --import stuff/key.gpg
          rm stuff/key.gpg
          python3 stuff/deploy_maven_central.py
